name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Verify hello action works
        uses: ./
  call-hello:
    runs-on: ubuntu-latest
    name: Hello
    steps:
      - name: Hello
        uses: kota999/github-actions-js-action-sample@v1.0.0
